### ISSUE TITLE
Stopped maintenance?

### ISSUE THREAD

**Issue by ioparaskev** [atoponce/d-note#49]
Is this project still maintained?

**Comment by JacobTheEvans** [comment]
Nope hasn't been for a while now its a shame.

**Comment by Thijssss** [comment]
I forked the project.

**Comment by atoponce** [comment]
No. This project is not dead. My family has been fostering kids the past year, and I've had zero time to give it the attention it deserves. I want to implement an API, I have some pull requests to create from XMission, and some clean up to do. Get a pull request, and I'll implement it.

**Comment by ioparaskev** [comment]
@atoponce no need to explain, I just asked to see if I can contribute and try to fix any issues or if the project is dead. Happy to hear it's not, take your time no need to apologize for anything :-)
